GET http://localhost:8080/api/elders/100
Accept: application/json

###


GET http://localhost:8080/api/elders
Accept: application/json

###
POST http://localhost:8080/api/elders
Content-Type: application/json

{
  "name": "Alma Barack",
  "dateOfBirth": [
    2021,
    6,
    30
  ]
}

###
PUT http://localhost:8080/api/elders/2/address
Content-Type: application/json
Accept: application/json

{
  "zipCode": "5400",
  "city": "Kamchatka",
  "street": "Street food",
  "houseNumber": "9"
}

###
PUT http://localhost:8080/api/finances
Content-Type: application/json
Accept: application/json

{
  "elderId": 1,
  "balance": 90000
}

###
POST http://localhost:8080/api/finances/elder/1/invoice
Content-Type: application/json

{
  "amount": -20000
}

###
GET http://localhost:8080/api/elders
Content-Type: application/json

{
  "name": "Alma Barack",
  "dateOfBirth": [
    2021,
    6,
    30
  ]
}

###
DELETE http://localhost:8080/api/elders/100/delete
