### Nem létező entitás lekérdezése
GET http://localhost:8080/api/elders/100
Accept: application/json

### Időszek listájának lekérdezése
GET http://localhost:8080/api/elders
Accept: application/json

### Idős hozzáadása
POST http://localhost:8080/api/elders
Content-Type: application/json

{
  "name": "John Doe",
  "dateOfBirth": [
    1950,
    6,
    30
  ]
}

### Validacio hibás név, hibás születési dátum
POST http://localhost:8080/api/elders
Content-Type: application/json

{
  "name": "John doe",
  "dateOfBirth": [
    2022,
    6,
    30
  ]
}

### Az id=1 elderhez hozzáadunk egy címet
PUT http://localhost:8080/api/elders/9/address
Content-Type: application/json
Accept: application/json

{
  "zipCode": "5400",
  "city": "Kamchatka",
  "street": "Street food",
  "houseNumber": "9"
}

### Létrehozza az 1-es id-jű elder pénzügyeit megadva a kiindulási egyenleget
PUT http://localhost:8080/api/finances
Content-Type: application/json
Accept: application/json

{
  "elderId": 11,
  "balance": 90000
}

###Validation, hozzá kell adni egy új eldert, mert egy elderhez csak egyszer lehet számlát hozzárendelni
PUT http://localhost:8080/api/finances
Content-Type: application/json
Accept: application/json

{
  "elderId": 2,
  "balance": -1
}

###Az 1-es id-jű elderhez hozzáadunk egy számlát
POST http://localhost:8080/api/finances/elder/11/invoice
Content-Type: application/json

{
  "amount": 20000,
  "description": "kjhkjg"
}


### 1-es Id-jű elder törlése
DELETE http://localhost:8080/api/elders/11/delete

### Hibakezelés
DELETE http://localhost:8080/api/elders/100/delete
